### ISSUE TITLE
env variables pre-filled example

### ISSUE THREAD

**Issue by uncodable** [otasoft/otasoft-core#66]
## Is your feature request related to a problem? Please describe.
.env.example to be pre-filled with example ports etc, remove the pain of manually entering every variable for first time setup.

**Comment by uncodable** [comment]
Example being missing:
`AUTH_POSTGRES_USERNAME`
`AUTH_POSTGRES_PASSWORD`
etc

**Comment by uncodable** [comment]
@Baroshem do you have these? makes it hard to start up the project without a correct `.env.example` thanks in advance.

**Comment by Baroshem** [comment]
Hi @uncodable 
Yes I will push the variables so that it will be easier to develop.

**Comment by Baroshem** [comment]
@uncodable 
Because Otasoft is built using microservices it may be easier to run each project separately with their own .env. I also added .env to Otasoft API which is a gateway used for handling all trafic and distributing it to the correct microservice. Let me know if you need more help.

**Comment by uncodable** [comment]
Thanks @Baroshem it was more for running docker-compose locally it needs the base .env i believe
